# Generated by Django 5.2.9 on 2025-12-21 09:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "full_refund_days",
                    models.IntegerField(
                        default=3, help_text="Дней для полного возврата"
                    ),
                ),
                ("partial_refund_enabled", models.BooleanField(default=True)),
                (
                    "min_refund_percentage",
                    models.IntegerField(
                        default=50,
                        help_text="Минимальный процент возврата для частичного возврата",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_refund_days",
                    models.IntegerField(
                        default=30,
                        help_text="Максимальное количество дней для возврата",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
